spring:
    application:
        name: board6
    datasource:
        url: jdbc:log4jdbc:mysql://localhost:3306/board
        username: root
        password: green502
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

logging:
    level:
        org.apache.ibatis: INFO

mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: mappers/**/*.xml
